server:
  port: 8085
  
spring:
  application:
    name: notification-service

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}    
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:admin}
    password: ${RABBITMQ_PASSWORD:admin}

rabbitmq:

  # ============================================
  # PROVIDER EVENT CONFIG
  # ============================================
  provider:
    exchange: ${RABBITMQ_PROVIDER_EXCHANGE:provider.exchange}

    routing:
      created: ${RABBITMQ_PROVIDER_ROUTING_CREATED:provider.created}
      updated: ${RABBITMQ_PROVIDER_ROUTING_UPDATED:provider.updated}
      deleted: ${RABBITMQ_PROVIDER_ROUTING_DELETED:provider.deleted}

    queue:
      created: ${RABBITMQ_PROVIDER_CREATED_QUEUE:provider.created.queue}
      updated: ${RABBITMQ_PROVIDER_UPDATED_QUEUE:provider.updated.queue}
      deleted: ${RABBITMQ_PROVIDER_DELETED_QUEUE:provider.deleted.queue}

    dlq:
      created: ${RABBITMQ_PROVIDER_DLQ_CREATED:provider.created.dlq}
      updated: ${RABBITMQ_PROVIDER_DLQ_UPDATED:provider.updated.dlq}
      deleted: ${RABBITMQ_PROVIDER_DLQ_DELETED:provider.deleted.dlq}

  # ============================================
  # USERS EVENT CONFIG
  # ============================================

  users:
    exchange: ${RABBITMQ_USERS_EXCHANGE:users.exchange}

    routing:
      created: ${RABBITMQ_USERS_ROUTING_CREATED:users.created}

    queue:
      created: ${RABBITMQ_USERS_CREATED_QUEUE:users.created.queue}

  # ============================================
  # BOOKING EVENT CONFIG
  # ============================================

  booking:
    exchange: ${RABBITMQ_BOOKING_EXCHANGE:booking.exchange}

    routing:
      created: ${RABBITMQ_BOOKING_ROUTING_CREATED:booking.created}
      updated: ${RABBITMQ_BOOKING_ROUTING_UPDATED:booking.updated}
      deleted: ${RABBITMQ_BOOKING_ROUTING_DELETED:booking.deleted}

    queue:
      created: booking.created.queue
      updated: booking.updated.queue
      deleted: booking.deleted.queue


resilience4j:
  retry:
    instances:
      bookingListenerRetry:
        max-attempts: 3
        wait-duration: 3s
      userListenerRetry:
        max-attempts: 3
        wait-duration: 3s
      providerListenerRetry:
        max-attempts: 3
        wait-duration: 3s
  ratelimiter:
    instances:
      bookingListenerRateLimiter:
        limit-for-period: 10
        limit-refresh-period: 20s
        timeout-duration: 0s
      userListenerRateLimiter:
        limit-for-period: 10
        limit-refresh-period: 20s
        timeout-duration: 0s
      providerListenerRateLimiter:
        limit-for-period: 10
        limit-refresh-period: 20s
        timeout-duration: 0s
  circuitbreaker:
    instances:
      bookingListenerCircuitBreaker:
        register-health-indicator: true
        sliding-window-size: 10
        failure-rate-threshold: 50
      userListenerCircuitBreaker:
        register-health-indicator: true
        sliding-window-size: 10
        failure-rate-threshold: 50
      providerListenerCircuitBreaker:
        register-health-indicator: true
        sliding-window-size: 10
        failure-rate-threshold: 50

logging:
  level:
    root: INFO