name: "Setup Testcontainers RabbitMQ"
description: "Configura RabbitMQ + environment variables + health check para integração"

inputs:
  use-env-file:
    description: "Carregar variáveis do .env"
    required: false
    default: "true"

runs:
  using: "composite"
  steps:

    - name: Iniciar serviço RabbitMQ
      shell: bash
      run: |
        echo "Iniciando RabbitMQ para Testcontainers..."
        docker run -d --rm \
          --name test-rabbitmq \
          -p 5672:5672 \
          -p 15672:15672 \
          -e RABBITMQ_DEFAULT_USER=admin \
          -e RABBITMQ_DEFAULT_PASS=admin \
          rabbitmq:3.13-management

    - name: Aguardar RabbitMQ ficar saudável
      shell: bash
      run: |
        echo "Aguardando RabbitMQ subir..."
        for i in {1..10}; do
          if docker exec test-rabbitmq rabbitmq-diagnostics -q ping; then
            echo "RabbitMQ está pronto!"
            exit 0
          fi
          echo "Aguardando..."
          sleep 3
        done
        echo "RabbitMQ falhou ao iniciar."
        exit 1

    - name: Carregar variáveis do .env
      if: ${{ inputs.use-env-file == 'true' }}
      shell: bash
      run: |
        if [ -f .env ]; then
          echo "Carregando .env..."
          export $(grep -v '^#' .env | xargs)
        else
          echo ".env não encontrado — ignorando."
        fi